# **Patients Data Cleaning**

## 1. Importing Libraries and Loading Data

In [79]:
import pandas as pd
import numpy as np

from pathlib import Path

import sys
sys.path.append(str(Path.cwd().parent))

from scripts.paths import RAW_DIR, CLEANED_DIR

df = pd.read_csv(RAW_DIR/"01_patients_dirty.csv")

## 2. Initial Data Inspection

In [80]:
df.head()

,Patient_ID,Patient_Name,Gender,DOB,Blood_Group,City,Phone,Insurance_Type,Registration_Date
0,P100000,Riya Sharma,Other,1944-07-18,Unknown,Bhopal,7726603341,Corporate,2026-01-05
1,P100001,Amit Verma,Male,1942-01-25,O-,Betul,8717592546,private,2025-07-20
2,P100002,Rahul Patel,Female,1993-07-14,B+,Betul,7388284972,NaN,2024-10-08
3,P100003,Riya Sahu,F,2013-03-14,B+,Indore,8945427018,Government,2025-09-02
4,P100004,Simran Gour,MALE,2015-06-19,B+,Itarsi,9316094791,Private,2025-07-25

In [81]:
df.shape

(8000, 9)

In [82]:
df.columns.tolist()

['Patient_ID',
 'Patient_Name',
 'Gender',
 'DOB',
 'Blood_Group',
 'City',
 'Phone',
 'Insurance_Type',
 'Registration_Date']

In [83]:
df.dtypes

Patient_ID           object
Patient_Name         object
Gender               object
DOB                  object
Blood_Group          object
City                 object
Phone                 int64
Insurance_Type       object
Registration_Date    object
dtype: object

In [84]:
df.isna().sum()

Patient_ID              0
Patient_Name            0
Gender                985
DOB                    40
Blood_Group           885
City                   63
Phone                   0
Insurance_Type       1002
Registration_Date       0
dtype: int64

In [85]:
df.duplicated().sum()

0

## 3. Audit of Specific Columns

In [86]:
df["Patient_ID"].duplicated().sum()

0

In [87]:
df["Patient_Name"].str.istitle().value_counts(dropna = False)

Patient_Name
True    8000
Name: count, dtype: int64

In [88]:
df["Gender"].unique()

array(['Other', 'Male', 'Female', 'F', 'MALE', 'M', 'female', nan,
       ' FEMALE', 'Male ', 'f', 'm'], dtype=object)

In [89]:
df["Gender"].nunique()

11

In [90]:
df["Blood_Group"].unique()

array(['Unknown', 'O-', 'B+', nan, 'A+', 'B-', 'A-', 'O+', 'AB+'],
      dtype=object)

In [91]:
df["Blood_Group"].nunique()

8

In [92]:
df["City"].unique()

array(['Bhopal', 'Betul', 'Indore', 'Itarsi', 'Dewas', 'Sehore',
       'Hoshangabad', 'Harda', 'Khandwa', 'Vidisha', nan, 'HARDA',
       'bhopal', ' harda', 'Indore '], dtype=object)

In [93]:
df["City"].nunique()

14

In [94]:
df["Insurance_Type"].unique()

array(['Corporate', 'private', nan, 'Government', 'Private', 'govt',
       'Self Pay', 'Cashless'], dtype=object)

In [95]:
df["Insurance_Type"].nunique()

7

In [96]:
df["DOB"].dtypes

dtype('O')

In [97]:
df["DOB"].isna().sum()

40

In [98]:
df["DOB"].head(20)

0     1944-07-18
1     1942-01-25
2     1993-07-14
3     2013-03-14
4     2015-06-19
5     1992-11-19
6     1986-03-17
7     1964-11-17
8     2001-05-23
9     1959-08-29
10    1962-05-05
11    1978-12-26
12    1950-08-26
13    2019-11-15
14    1948-09-06
15    2004-11-11
16    2014-11-30
17    1961-12-01
18    1979-12-25
19    1947-05-26
Name: DOB, dtype: object

In [99]:
dob_converted = pd.to_datetime(df["DOB"], errors = "coerce")
dob_converted

0      1944-07-18
1      1942-01-25
2      1993-07-14
3      2013-03-14
4      2015-06-19
          ...
7995   2018-11-13
7996          NaT
7997   2010-03-08
7998   1997-05-28
7999   1954-06-26
Name: DOB, Length: 8000, dtype: datetime64[ns]

In [100]:
dob_converted.dtype

dtype('<M8[ns]')

In [101]:
dob_converted.isna().sum()

40

In [102]:
df.loc[dob_converted.isna(), "DOB"]

239     NaN
265     NaN
296     NaN
390     NaN
598     NaN
861     NaN
876     NaN
951     NaN
1117    NaN
1132    NaN
1216    NaN
1327    NaN
1542    NaN
1593    NaN
2022    NaN
2247    NaN
2310    NaN
2445    NaN
2563    NaN
3604    NaN
4271    NaN
4682    NaN
4755    NaN
4782    NaN
5040    NaN
5503    NaN
5906    NaN
6017    NaN
6108    NaN
6119    NaN
6661    NaN
6868    NaN
6993    NaN
7219    NaN
7256    NaN
7408    NaN
7714    NaN
7937    NaN
7949    NaN
7996    NaN
Name: DOB, dtype: object

In [103]:
registration_converted = pd.to_datetime(df["Registration_Date"], errors = "coerce")
registration_converted

0      2026-01-05
1      2025-07-20
2      2024-10-08
3      2025-09-02
4      2025-07-25
          ...
7995   2025-02-03
7996   2025-03-18
7997   2026-08-27
7998   2025-06-13
7999   2024-01-11
Name: Registration_Date, Length: 8000, dtype: datetime64[ns]

In [104]:
(dob_converted > registration_converted).sum()

0

In [105]:
display(dob_converted.min())
display(dob_converted.max())

Timestamp('1940-01-03 00:00:00')

Timestamp('2022-02-18 00:00:00')

In [106]:
display(registration_converted.min())
display(registration_converted.max())

Timestamp('2024-01-01 00:00:00')

Timestamp('2026-08-28 00:00:00')

In [107]:
df["Phone"].dtype

dtype('int64')

In [108]:
df["Phone"].isna().sum()

0

In [109]:
df["Phone"].duplicated().sum()

0

In [110]:
phone_text = df["Phone"].astype(str)
phone_text

0       7726603341
1       8717592546
2       7388284972
3       8945427018
4       9316094791
           ...
7995    6967337658
7996    9941098871
7997    9630584300
7998    9958847341
7999    7708460207
Name: Phone, Length: 8000, dtype: object

In [111]:
phone_text.str.len().value_counts()

Phone
10    7780
7       50
4       46
6       44
5       41
8       39
Name: count, dtype: int64

In [112]:
df.loc[phone_text.str.len()  != 10, "Phone"]

80        714506
145     82181022
228      9895720
315     72143296
328      7267757
          ...
7821    83768348
7837     8664313
7942        8581
7951        9691
7988     8774982
Name: Phone, Length: 220, dtype: int64

In [113]:
phone_text.str.contains(r"\D").sum()

0

## 4. Data Cleaning

In [114]:
df.head()

,Patient_ID,Patient_Name,Gender,DOB,Blood_Group,City,Phone,Insurance_Type,Registration_Date
0,P100000,Riya Sharma,Other,1944-07-18,Unknown,Bhopal,7726603341,Corporate,2026-01-05
1,P100001,Amit Verma,Male,1942-01-25,O-,Betul,8717592546,private,2025-07-20
2,P100002,Rahul Patel,Female,1993-07-14,B+,Betul,7388284972,NaN,2024-10-08
3,P100003,Riya Sahu,F,2013-03-14,B+,Indore,8945427018,Government,2025-09-02
4,P100004,Simran Gour,MALE,2015-06-19,B+,Itarsi,9316094791,Private,2025-07-25

### 4.1 Gender

In [115]:
Gender_cleaned = df["Gender"].str.strip().str.lower()

In [116]:
Gender_cleaned.unique()

array(['other', 'male', 'female', 'f', 'm', nan], dtype=object)

In [117]:
Gender_cleaned = Gender_cleaned.replace(
    {
        "male": "Male",
        "female": "Female",
        "m": "Male",
        "f": "Female",
        "other": "Other"
    }
)

In [118]:
display(Gender_cleaned.unique())
display(Gender_cleaned.nunique())

array(['Other', 'Male', 'Female', nan], dtype=object)

3

In [119]:
Gender_cleaned.isna().sum()

985

In [120]:
Gender_cleaned.value_counts(dropna = False)

Gender
Female    3063
Male      2961
Other      991
NaN        985
Name: count, dtype: int64

In [121]:
df["Gender"] = Gender_cleaned

In [122]:
df["Gender"].unique()

array(['Other', 'Male', 'Female', nan], dtype=object)

### 4.2 Blood Group

In [123]:
df["Blood_Group"].value_counts(dropna = False)

Blood_Group
O-         926
Unknown    911
O+         909
B-         898
A+         894
AB+        890
NaN        885
A-         854
B+         833
Name: count, dtype: int64

In [124]:
df["Blood_Group"].unique()

array(['Unknown', 'O-', 'B+', nan, 'A+', 'B-', 'A-', 'O+', 'AB+'],
      dtype=object)

In [125]:
df["Blood_Group"].isna().sum()

885

### 4.3 City

In [126]:
city_cleaned = df["City"].str.strip().str.lower()
city_cleaned.unique()

array(['bhopal', 'betul', 'indore', 'itarsi', 'dewas', 'sehore',
       'hoshangabad', 'harda', 'khandwa', 'vidisha', nan], dtype=object)

In [127]:
city_cleaned = city_cleaned.str.title()
city_cleaned.unique()

array(['Bhopal', 'Betul', 'Indore', 'Itarsi', 'Dewas', 'Sehore',
       'Hoshangabad', 'Harda', 'Khandwa', 'Vidisha', nan], dtype=object)

In [128]:
city_cleaned.isna().sum()

63

In [129]:
df["City"] = city_cleaned

In [130]:
df["City"].unique()

array(['Bhopal', 'Betul', 'Indore', 'Itarsi', 'Dewas', 'Sehore',
       'Hoshangabad', 'Harda', 'Khandwa', 'Vidisha', nan], dtype=object)

### 4.4 Insurance Type

In [131]:
display(df["Insurance_Type"].unique())
display(df["Insurance_Type"].nunique())

array(['Corporate', 'private', nan, 'Government', 'Private', 'govt',
       'Self Pay', 'Cashless'], dtype=object)

7

In [132]:
Insurance_cleaned = df["Insurance_Type"].str.strip().str.title()
Insurance_cleaned

0        Corporate
1          Private
2              NaN
3       Government
4          Private
           ...
7995       Private
7996       Private
7997      Self Pay
7998    Government
7999          Govt
Name: Insurance_Type, Length: 8000, dtype: object

In [133]:
Insurance_cleaned.unique()

array(['Corporate', 'Private', nan, 'Government', 'Govt', 'Self Pay',
       'Cashless'], dtype=object)

In [134]:
Insurance_cleaned = Insurance_cleaned.replace(
    {
        "Govt": "Government"
    }
)

In [135]:
display(Insurance_cleaned.unique())
display(Insurance_cleaned.nunique())

array(['Corporate', 'Private', nan, 'Government', 'Self Pay', 'Cashless'],
      dtype=object)

5

In [136]:
Insurance_cleaned.isna().sum()

1002

In [137]:
df["Insurance_Type"] = Insurance_cleaned
df["Insurance_Type"].unique()

array(['Corporate', 'Private', nan, 'Government', 'Self Pay', 'Cashless'],
      dtype=object)

### 4.5 DOB

In [138]:
df["DOB"] = dob_converted
display(df["DOB"].isna().sum())
display(df["DOB"].dtype)

40

dtype('<M8[ns]')

### 4.6 Registration Date

In [139]:
registration_converted.dtype

dtype('<M8[ns]')

In [140]:
registration_converted.isna().sum()

0

In [141]:
df["Registration_Date"] = registration_converted
df["Registration_Date"].dtype

dtype('<M8[ns]')

### 4.7 Phone

In [142]:
phone_text = phone_text.mask(phone_text.str.len() != 10)

In [143]:
phone_text.isna().sum()

220

In [144]:
df["Phone"] = phone_text

In [145]:
df["Phone"].isna().sum()

220

In [146]:
df["Phone"].dtype

dtype('O')

## 5. Final Validation

In [147]:
df.shape

(8000, 9)

In [148]:
df.isna().sum()

Patient_ID              0
Patient_Name            0
Gender                985
DOB                    40
Blood_Group           885
City                   63
Phone                 220
Insurance_Type       1002
Registration_Date       0
dtype: int64

In [149]:
df.duplicated().sum()

0

In [150]:
df["Gender"].unique()

array(['Other', 'Male', 'Female', nan], dtype=object)

In [151]:
df["Blood_Group"].unique()

array(['Unknown', 'O-', 'B+', nan, 'A+', 'B-', 'A-', 'O+', 'AB+'],
      dtype=object)

In [152]:
df["City"].unique()

array(['Bhopal', 'Betul', 'Indore', 'Itarsi', 'Dewas', 'Sehore',
       'Hoshangabad', 'Harda', 'Khandwa', 'Vidisha', nan], dtype=object)

In [153]:
df["Insurance_Type"].unique()

array(['Corporate', 'Private', nan, 'Government', 'Self Pay', 'Cashless'],
      dtype=object)

In [154]:
df.dtypes

Patient_ID                   object
Patient_Name                 object
Gender                       object
DOB                  datetime64[ns]
Blood_Group                  object
City                         object
Phone                        object
Insurance_Type               object
Registration_Date    datetime64[ns]
dtype: object

In [155]:
(df["DOB"] > df["Registration_Date"]).sum()

0

## 6. Export Cleaned Data

In [156]:
df.to_csv(CLEANED_DIR/"01_patients_cleaned.csv", index = False)